# Generated by Django 4.1.6 on 2023-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
